#!/usr/bin/env sh

/opt/homebrew/bin/yabai -m signal --add event=dock_did_restart action="sudo /opt/homebrew/bin/yabai --load-sa"
/opt/homebrew/bin/yabai -m signal --add event=window_focused   action="sketchybar --trigger window_focus"
/opt/homebrew/bin/yabai -m signal --add event=window_created   action="sketchybar --trigger windows_on_spaces"
/opt/homebrew/bin/yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
# See: https://github.com/koekeishiya/yabai/issues/719
# focus window after active space changes
/opt/homebrew/bin/yabai -m signal --add event=space_changed    action="/opt/homebrew/bin/yabai -m window --focus \$(/opt/homebrew/bin/yabai -m query --windows --space | jq .[0].id)"
# focus window after active display changes
/opt/homebrew/bin/yabai -m signal --add event=display_changed  action="/opt/homebrew/bin/yabai -m window --focus \$(/opt/homebrew/bin/yabai -m query --windows --space | jq .[0].id)"

# See:  https://github.com/AdamWagner/stackline/issues/110
EVENT_TYPES=(
    display_added
    display_removed
    display_changed
    space_changed
    application_visible
    application_hidden
    window_created
    window_destroyed
)
for event in ${EVENT_TYPES[@]}; do
    /opt/homebrew/bin/yabai -m signal --add event=$event action="hs -A -c 'stackline.manager:update({forceRedraw = true})'"
done

sudo /opt/homebrew/bin/yabai --load-sa

# global settings
/opt/homebrew/bin/yabai -m config mouse_follows_focus          off
/opt/homebrew/bin/yabai -m config focus_follows_mouse          off
/opt/homebrew/bin/yabai -m config window_origin_display        default
/opt/homebrew/bin/yabai -m config window_placement             second_child
/opt/homebrew/bin/yabai -m config window_topmost               off
/opt/homebrew/bin/yabai -m config window_shadow                on
/opt/homebrew/bin/yabai -m config window_opacity               off
/opt/homebrew/bin/yabai -m config insert_feedback_color        0xffd75f5f
/opt/homebrew/bin/yabai -m config auto_balance                 off
/opt/homebrew/bin/yabai -m config mouse_modifier               fn
/opt/homebrew/bin/yabai -m config mouse_action1                move
/opt/homebrew/bin/yabai -m config mouse_action2                resize
/opt/homebrew/bin/yabai -m config mouse_drop_action            swap

# general space settings
/opt/homebrew/bin/yabai -m config layout                       bsp
/opt/homebrew/bin/yabai -m config window_gap                   13
/opt/homebrew/bin/yabai -m config top_padding                  10
/opt/homebrew/bin/yabai -m config bottom_padding               10
/opt/homebrew/bin/yabai -m config left_padding                 10
/opt/homebrew/bin/yabai -m config right_padding                10
/opt/homebrew/bin/yabai -m config window_animation_duration    0.1

# integration with Sketchybar
/opt/homebrew/bin/yabai -m config external_bar all:0:30

# rules for specific apps
/opt/homebrew/bin/yabai -m rule --add app="^iStat*" sticky=on layer=above manage=off border=off
/opt/homebrew/bin/yabai -m rule --add app="^系统设置*" manage=off
/opt/homebrew/bin/yabai -m rule --add app="^Grammarly*" manage=off
/opt/homebrew/bin/yabai -m rule --add app="^(Wechat|微信)" title="通用" manage=off
/opt/homebrew/bin/yabai -m rule --add app="^(计算器|VLC|系统设置|AppCleaner|zoom.us|Inkscape Settings|活动监视器)$" manage=off
/opt/homebrew/bin/yabai -m rule --add app="^Inkscape$" title="" manage=off

/opt/homebrew/bin/borders active_color=0xff2cf9ed inactive_color=0xff494d64 width=8.0 hidpi=on &
