#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

# load predefined colors
source "$CONFIG_DIR/colors.sh"

sketchybar --add event aerospace_workspace_change

sketchybar --bar height=37        \
                 blur_radius=30   \
                 position=bottom  \
                 sticky=off       \
                 padding_left=10  \
                 padding_right=10 \
                 color=$BAR_COLOR

sketchybar --default icon.font="SF Pro:Semibold:15.0"  \
                     icon.color=$WHITE                 \
                     label.font="SF Pro:Semibold:15.0" \
                     label.color=$WHITE                \
                     background.color=$ITEM_BG_COLOR   \
                     background.corner_radius=5        \
                     background.height=24              \
                     padding_left=5                    \
                     padding_right=5                   \
                     label.padding_left=4              \
                     label.padding_right=10            \
                     icon.padding_left=10              \
                     icon.padding_right=4

##### Adding Left Items #####
##### Adding Aerospace Workspace Indicators #####
for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
               --subscribe space.$sid aerospace_workspace_change   \
               --set space.$sid                                    \
                     icon=$sid                                     \
                     label.font="sketchybar-app-font:Regular:16.0" \
                     label.padding_right=20                        \
                     label.y_offset=-1                             \
                     click_script="aerospace workspace $sid"       \
                     script="$PLUGIN_DIR/space.sh $sid"
done

sketchybar --add item space_separator left                             \
           --set space_separator icon="􀆊"                              \
                                 icon.color=$ACCENT_COLOR              \
                                 icon.padding_left=4                   \
                                 label.drawing=off                     \
                                 background.drawing=off                \
                                 script="$PLUGIN_DIR/space_windows.sh" \
           --subscribe space_separator space_windows_change

sketchybar --add item front_app left                                         \
           --set front_app      background.color=$ACCENT_COLOR               \
                                icon.color=$BAR_COLOR                        \
                                icon.font="sketchybar-app-font:Regular:16.0" \
                                label.color=$BAR_COLOR                       \
                                script="$PLUGIN_DIR/front_app.sh"            \
           --subscribe front_app front_app_switched

sketchybar --update
