gui:
  language: 'en'
  timeFormat: '2015-02-25 11:06'
  showIcons: true

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

os:
  editCommand: 'vim'
  editCommandTemplate: '{{editor}} +{{line}} -- {{filename}}'
